### PR TITLE
adapt https://github.com/paritytech/polkadot-sdk/pull/1234 (UMP price for delivery + benchmarks compilation)

### PR DESCRIPTION
**Pull request by bkontur**

### CODE REVIEW

**Comment by bkontur** [comment]
@svyatonik @franciscoaguirre

**Comment by franciscoaguirre** [comment]
Awesome! Thank you for doing this. I was going to wait until the upgrade was done, but better to be ready

It's only missing the FeeManager to put fees in the treasury

**Review by svyatonik — APPROVED** [review]
> It's only missing the FeeManager to put fees in the treasury

Thanks, @bkontur . I could merge as is and we could add that ^^ later, or do you plan to add it in this PR?

**Comment by bkontur** [comment]
ok, lets merge, I will prepare another PR

**Pull request merged**
